using System.Globalization;
using System.Text;

namespace KREAN.MapCompiler;

/// <summary>Writes <see cref="MapEntity"/> lists back to the Quake .map text format.</summary>
public static class MapWriter
{
    public static void Write(string path, List<MapEntity> entities)
    {
        File.WriteAllText(path, Serialize(entities));
    }

    public static string Serialize(List<MapEntity> entities)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by KREAN.MapEditor");

        for (int ei = 0; ei < entities.Count; ei++)
        {
            var e = entities[ei];
            sb.AppendLine("{");
            foreach (var (k, v) in e.Properties)
                sb.AppendLine($"\"{Escape(k)}\" \"{Escape(v)}\"");

            foreach (var brush in e.Brushes)
            {
                sb.AppendLine("{");
                foreach (var face in brush.Faces)
                {
                    string p1 = Vec(face.P1);
                    string p2 = Vec(face.P2);
                    string p3 = Vec(face.P3);
                    string tex = face.Texture.Length == 0 ? "nodraw" : face.Texture;

                    if (face.IsValve)
                    {
                        // Valve 220: ( p1 ) ( p2 ) ( p3 ) tex [ ux uy uz off ] [ vx vy vz off ] rot sx sy
                        sb.AppendLine(
                            $"{p1} {p2} {p3} {tex} " +
                            $"[ {F(face.UAxis.X)} {F(face.UAxis.Y)} {F(face.UAxis.Z)} {F(face.UOffset)} ] " +
                            $"[ {F(face.VAxis.X)} {F(face.VAxis.Y)} {F(face.VAxis.Z)} {F(face.VOffset)} ] " +
                            $"{F(face.Rotation)} {F(face.ScaleX)} {F(face.ScaleY)}");
                    }
                    else
                    {
                        sb.AppendLine($"{p1} {p2} {p3} {tex} {F(face.UOffset)} {F(face.VOffset)} {F(face.Rotation)} {F(face.ScaleX)} {F(face.ScaleY)}");
                    }
                }
                sb.AppendLine("}");
            }
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

    static string Vec(System.Numerics.Vector3 v) =>
        $"( {F(v.X)} {F(v.Y)} {F(v.Z)} )";

    static string F(float f) => f.ToString("0.######", CultureInfo.InvariantCulture);

    static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
